export type User = {
  nome: string;
  estadocivil: string;
  cep: string;
  segundo_bairro: string;
  identidade: string;
  categoria: string;
  pai: string;
  numero: string;
  validade_cr: string;
  naturalidade: string;
  segundo_obs: string;
  cidade: string;
  cr: string;
  data_exped: string;
  siglauf: string;
  bairro: string;
  profissao: string;
  segundo_rua: string;
  termos_idoneidade: boolean | string;
  segundo_cidade: string;
  segundo_estado: string;
  cpf: string;
  segundo_cep: string;
  termos_estatuto: boolean | string;
  tituloeleitoral: string;
  data_renovacao: string;
  nacionalidade: string;
  orgaouf: string;
  matricula: string | number;
  mae: string;
  data_nascimento: string;
  termos_filiacao: boolean | string;
  telefone: string;
  segundo_num: string;
  email: string;
  data_filiacao: string;
  rua: string;
  instagram: string;
  id: string;
};
